version: '2'

services:
    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
    tcgplace-cards-db:
      image: mysql:5.7
      container_name: tcgplace_db
      restart: always
      volumes:
      - data:/var/lib/mysql    
      - ./db/scripts:/docker-entrypoint-initdb.d
      ports:
      - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: tcgplace
    web:
        build: .
        ports:
        - "5000:5000"
volumes:
    data:
